
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog-jm_production
  username: blog-jm
  password: <%= ENV['BLOG-JM_DATABASE_PASSWORD'] %>